In [1]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import csv
import json

In [3]:
url="https://api.covid19api.com/dayone/country/united-states"
response = requests.get(url).json()
#print(json.dumps(response, indent=4, sort_keys=True))
df = pd.DataFrame(response)

In [4]:
df.head(15)

,Country,CountryCode,Province,City,CityCode,Lat,Lon,Confirmed,Deaths,Recovered,Active,Date
0,United States of America,US,Washington,King,53033,47.49,-121.83,1,0,0,0,2020-01-23T00:00:00Z
1,United States of America,US,Washington,King,53033,47.49,-121.83,1,0,0,0,2020-01-24T00:00:00Z
2,United States of America,US,Illinois,Cook,17031,41.84,-87.82,1,0,0,0,2020-01-24T00:00:00Z
3,United States of America,US,Illinois,Cook,17031,41.84,-87.82,1,0,0,0,2020-01-25T00:00:00Z
4,United States of America,US,Washington,King,53033,47.49,-121.83,1,0,0,0,2020-01-25T00:00:00Z
5,United States of America,US,Washington,King,53033,47.49,-121.83,1,0,0,0,2020-01-26T00:00:00Z
6,United States of America,US,Illinois,Cook,17031,41.84,-87.82,1,0,0,0,2020-01-26T00:00:00Z
7,United States of America,US,Arizona,Maricopa,4013,33.35,-112.49,1,0,0,0,2020-01-26T00:00:00Z
8,United States of America,US,California,Orange,6059,33.7,-117.76,1,0,0,0,2020-01-26T00:00:00Z
9,United States of America,US,California,Los Angeles,6037,34.31,-118.23,1,0,0,0,2020-01-26T00:00:00Z
10,United States of America,US,California,Los Angeles,6037,34.31,-118.23,1,0,0,0,2020-01-27T00:00:00Z
11,United States of America,US,Illinois,Cook,17031,41.84,-87.82,1,0,0,0,2020-01-27T00:00:00Z
12,United States of America,US,California,Orange,6059,33.7,-117.76,1,0,0,0,2020-01-27T00:00:00Z
13,United States of America,US,Arizona,Maricopa,4013,33.35,-112.49,1,0,0,0,2020-01-27T00:00:00Z
14,United States of America,US,Washington,King,53033,47.49,-121.83,1,0,0,0,2020-01-27T00:00:00Z